---
title: "Real Data Finally"
author: "Benyomin Hagalili"
date: "9/2/2016"
output: html_document
#output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Use real data from Israel.
# data wrangle to match form of USA data.
# plot w/ boxplot.

[code gist](https://gist.github.com/paynito/d15f0ba71646ae34acaffedb70d85193)
```{r create data}
# duplicate 1 # to make a mode
nyc_income1984 <- c(4,246,24,34,234,553,34)
dfw_income1984 <- c(344, 423,522, 234, 522, 255)
okc_income1984 <-c(234,234,236,99,184,301)
      # pad any short columns with NA
max.len = max(length(nyc_income1984),length(dfw_income1984),length(okc_income1984))
nyc1984 <-c(nyc_income1984, rep(NA, max.len-length(nyc_income1984)))
dfw1984 <-c(dfw_income1984, rep(NA, max.len-length(dfw_income1984)))
okc1984 <-c(okc_income1984,rep(NA,  max.len-length(okc_income1984)))
nyc1985 <- nyc1984*1.4
dfw1985 <- dfw1984+50
okc1985 <- okc1984*.7
nyc1986 <- nyc1984*.8
dfw1986 <- dfw1984*1.2
okc1986 <- okc1984*1.3
location <- c('NYC','DFW','OKC')
cityName <- tolower(location)
year<- c(1984,1984,1984,1985,1985,1985,1986,1986,1986)
library(reshape2)
all.data = data.frame(rbind
                           (nyc1984,dfw1984,okc1984,
                             nyc1985,dfw1985,okc1985,
                             nyc1986,dfw1986,okc1986)
                      )
all.data$location <- location
all.data$year     <- year
stacked.data = melt(all.data,id =c('location','year'))
head(stacked.data)
incomeByCity <- stacked.data[,-3]
boxplots.triple = boxplot(value~location+year,
                          data = incomeByCity,
                          ylab = "$/month",
                          las = 2,
                          ylim=c(0,800),
                          col = c("sienna","palevioletred1","royalblue2")
                          )
# jpeg('groupedBoxPlots3.jpg')
     boxplots.triple
    # text(c(1,1.8,2.6,6,6.8,7.6),c(6,8,1,17.5,20,15.5),location)
    # axis(side=1, at=c(1.8,6.8,10.5), labels=c(1984,1985,1986))
     title('Individual Income in 3 cities, 1984-86')       
                                        # dev.off()
library(foreign)
library(Hmisc)
require(ggplot2)
require(dplyr)
library(tidyr)
file456 <- spss.get("/Users/AbuDavid/school/census/f456/f456ind.por", use.value.labels=TRUE)
subSetInd2014<-dplyr::select(file456,YEARSUR,WPLDIST,USSRBORN,INCSAL)
## refactor  Cities first
## remove USSR Born data
center2014 <- subSetInd2014 %>% dplyr::filter(WPLDIST=="Center") %>% select(-USSRBORN)
telAviv2014 <- subSetInd2014 %>% dplyr::filter(WPLDIST=="Tel-Aviv") %>% select(-USSRBORN)
gushDan2014 <- subSetInd2014 %>% dplyr::filter(WPLDIST=="Gush Dan") %>% select(-USSRBORN)
head(gushDan2014)
head(incomeByCity)
# rename columns to US-style
center2014<-center2014 %>%  







 ##            # reorder by column name
##  subCitiesIND2014 <- subCitiesInd2014[c("WPLDIST","YEARSUR","INCSAL")]
##  Israel2014 <-subCitiesIND2014 %>%rename("WPLDIST" ="location") 
##  Israel2014 <-subCitiesIND2014 %>%rename(year = YEARSUR)
##  Israel2014 <-subCitiesIND2014 %>%rename(value = INCSAL )
## head(Israel2014$year)
## head(Israel2014$location)
## head(subCitiesIND2014)

                   length(Israel2014$location)
##       count(Israel2014$location=="Center")
##         count(Israel2014$location=="Gush Dan")
##  count(Israel2014$location=="Tel-Aviv")
##
##   previous code used
##   all.data = data.frame(rbind
##                            (nyc1984,dfw1984,okc1984,
##                              nyc1985,dfw1985,okc1985,
##                              nyc1986,dfw1986,okc1986))
## all.data$location <- location
## all.data$year     <- year
## stacked.data = melt(all.data,id =c('location','year'))

    ```
* Some words after final code block.
** The opposite of tidyr::gather is spread.
** The opposite of reshape2::melt is separate() or colsplit().
```{r plot5}
#tidyr::spread(Israel2014)
Israel2014 %>% filter(location=="Center")

```
